[project]
name = "ocr-llamavision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-core>=0.3.74",
    "langchain-ollama>=0.3.6",
    "ollama>=0.5.3",
    "pandas>=2.3.1",
]
